[package]
name = "mumdia-io"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mumdia-core = { path = "../mumdia-core" }
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
blake3.workspace = true
arrow.workspace = true
parquet.workspace = true
