name: Test Status Badge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-status:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test_requirements.txt
        pip install -e .
    
    - name: Run quick test suite
      run: |
        python -m pytest tests/ -v --tb=short --maxfail=5 -x
    
    - name: Update test status
      if: always()
      run: |
        if [ $? -eq 0 ]; then
          echo "Tests passing ✅" >> $GITHUB_STEP_SUMMARY
        else
          echo "Tests failing ❌" >> $GITHUB_STEP_SUMMARY
        fi
